# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='rater',
            name='ratings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Ratings'),
        ),
        migrations.AddField(
            model_name='movies',
            name='ratings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Ratings'),
        ),
    ]
